demo_r_mwk3_t.tsv:
# via https://ec.europa.eu/eurostat/web/population-demography-migration-projections/data/database
	wget -O demo_r_mwk3_t.tsv.gz "https://ec.europa.eu/eurostat/estat-navtree-portlet-prod/BulkDownloadListing?file=data/demo_r_mwk3_t.tsv.gz"
	gunzip demo_r_mwk3_t.tsv.gz

demo_r_mwk_ts.tsv:
	wget -O demo_r_mwk_ts.tsv.gz "https://ec.europa.eu/eurostat/estat-navtree-portlet-prod/BulkDownloadListing?file=data/demo_r_mwk_ts.tsv.gz"
	gunzip demo_r_mwk_ts.tsv.gz
