
ts-d-14.03.04.03-wr.csv:
# via https://www.bfs.admin.ch/bfs/de/home/statistiken/gesundheit/gesundheitszustand/sterblichkeit-todesursachen.html
	wget -O ts-d-14.03.04.03-wr.csv "https://www.bfs.admin.ch/bfsstatic/dam/assets/15084083/master"

ts-d-14.03.04.03-wr_ZR.csv:
# via https://www.bfs.admin.ch/bfs/de/home/statistiken/gesundheit/gesundheitszustand/sterblichkeit-todesursachen.html
	wget -O ts-d-14.03.04.03-wr_ZR.csv "https://www.bfs.admin.ch/bfsstatic/dam/assets/12607336/master"
